[build]
  command = "yarn install && yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200